[build]
nixpacksVersion = "1.20.0"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:3000 -t public"