[build]
nixpacksVersion = "1.20.0"

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm install",
  "php artisan view:cache",
  "php artisan migrate --force",
  "php artisan db:seed"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -S 0.0.0.0:3000 -t public"